#!/usr/bin/env bash

# Copyright (C) 2026 Intel Corporation
# SPDX-License-Identifier: BSD-3-Clause
#
# schematic_dev_mode.sh
# Configures Schematic Viewer development dependency overrides.
#
# 2026 August
# Author: Desmond Kirkpatrick <desmond.a.kirkpatrick@intel.com>

set -euo pipefail

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
viewer_dir="$(cd -- "$script_dir/.." && pwd)"
cd "$viewer_dir"

mode="${1:-}"
overrides="pubspec_overrides.yaml"
source_state=".schematic_dependency_sources"
marker="# Generated by scripts/schematic_dev_mode.sh. Do not edit by hand."
default_rohd_path="$HOME/release/rohd"
rohd_git_url="${ROHD_GIT_URL:-https://github.com/intel/rohd.git}"
rohd_git_ref="${ROHD_GIT_REF:-main}"
temporary_files=()
temporary_file=""
configured_overrides_required=0

cleanup_temporary_files() {
  if [[ "${#temporary_files[@]}" -gt 0 ]]; then
    rm -f -- "${temporary_files[@]}"
  fi
}

create_temporary_file() {
  temporary_file="$(mktemp "$viewer_dir/.schematic_dev_mode.XXXXXX")"
  temporary_files+=("$temporary_file")
}

trap cleanup_temporary_files EXIT

dependency_constraint() {
  local package="$1"
  awk -v package="$package" '
    $1 == package ":" { print $2; exit }
  ' pubspec.yaml
}

for dependency in rohd rohd_hierarchy rohd_devtools_widgets rohd_source_navigator; do
  if [[ -z "$(dependency_constraint "$dependency")" ]]; then
    echo "Could not find $dependency in pubspec.yaml." >&2
    exit 1
  fi
done

rohd_path="${ROHD_LOCAL_PATH:-$default_rohd_path}"

usage() {
  cat <<'USAGE'
Usage: scripts/schematic_dev_mode.sh <mode>

Configure individual package sources:
  scripts/schematic_dev_mode.sh configure <package> <source> ...
  where each source is hosted, git, or local.

For example:
  scripts/schematic_dev_mode.sh configure rohd git rohd_hierarchy local

Modes:
  manifest         Disable overrides and use pubspec.yaml sources.
  configure-group  Configure one dependency group or all dependencies.
  local-rohd       Local ROHD + hierarchy; hosted extension packages.
  local-extension  Hosted ROHD; local hierarchy + extension packages.
  local-all        Local ROHD, hierarchy, and DevTools-extension packages.
  show             Print the current generated override file, if present.

The default local ROHD checkout is ~/release/rohd.
Set ROHD_LOCAL_PATH to use a different checkout.

All Git-backed groups share one ROHD_GIT_URL and ROHD_GIT_REF because every
configured package comes from the ROHD monorepo. All Local-backed groups
likewise share one ROHD_LOCAL_PATH. Changing either shared setting while
configuring one group updates every other group that uses that source, without
changing the other groups' hosted/git/local selections.

Git sources default to the main branch. Set ROHD_GIT_REF to use another branch
or tag.

Set SCHEMATIC_PROMPT_SOURCE_VALUE=1 with configure-group to prompt for a Git
repository:ref or Local checkout path. Set ROHD_SOURCE_VALUE to provide the
same value non-interactively.

With no overrides, the hosted dependencies in pubspec.yaml are used.

Legacy aliases hr-he, lr-he, hr-le, and lr-le remain supported.
USAGE
}

ensure_managed_or_absent() {
  if [[ -f "$overrides" ]] && ! grep -qxF "$marker" "$overrides"; then
    echo "$overrides exists and was not generated by scripts/schematic_dev_mode.sh." >&2
    echo "Move or remove it before switching development modes." >&2
    exit 1
  fi
}

backup_overrides() {
  local backup="$overrides.disabled"
  local suffix=1

  if [[ ! -f "$overrides" ]]; then
    return
  fi

  while [[ -e "$backup" ]]; do
    backup="$overrides.disabled.$suffix"
    suffix=$((suffix + 1))
  done
  mv -- "$overrides" "$backup"
  echo "Saved the previous $overrides as $backup."
}

resolve_rohd_path() {
  case "$rohd_path" in
    '~') rohd_path="$HOME" ;;
    \~/*) rohd_path="$HOME/${rohd_path:2}" ;;
  esac
  if [[ ! -f "$rohd_path/pubspec.yaml" ]] || ! grep -qx 'name: rohd' "$rohd_path/pubspec.yaml"; then
    echo "Could not find a ROHD checkout at $rohd_path." >&2
    echo "Set ROHD_LOCAL_PATH to a checkout rooted at the rohd package." >&2
    exit 1
  fi
  rohd_path="$(cd -- "$rohd_path" && pwd)"
}

resolve_widgets_path() {
  local widgets_path="$rohd_path/packages/rohd_devtools_widgets"
  if [[ ! -f "$widgets_path/pubspec.yaml" ]]; then
    widgets_path="$rohd_path/rohd_devtools_extension/packages/rohd_devtools_widgets"
  fi
  printf '%s\n' "$widgets_path"
}

resolve_navigator_path() {
  local navigator_path="$rohd_path/packages/rohd_source_navigator"
  if [[ ! -f "$navigator_path/pubspec.yaml" ]]; then
    navigator_path="$rohd_path/rohd_extension/dart"
  fi
  printf '%s\n' "$navigator_path"
}

ensure_local_rohd_packages() {
  local require_extension="$1"
  local missing=0

  if [[ ! -f "$rohd_path/packages/rohd_hierarchy/pubspec.yaml" ]]; then
    echo "Missing local ROHD package: $rohd_path/packages/rohd_hierarchy/pubspec.yaml" >&2
    missing=1
  fi

  if [[ "$require_extension" == "yes" ]]; then
    local widgets_path
    local navigator_path
    widgets_path="$(resolve_widgets_path)"
    navigator_path="$(resolve_navigator_path)"
    for package_path in "$widgets_path/pubspec.yaml" \
      "$navigator_path/pubspec.yaml"; do
      if [[ ! -f "$package_path" ]]; then
        echo "Missing local ROHD package: $package_path" >&2
        missing=1
      fi
    done
  fi

  if [[ "$missing" != "0" ]]; then
    echo "Use a ROHD checkout with the split-package layout, or choose the manifest mode." >&2
    exit 1
  fi
}

validate_source() {
  case "$1" in
    hosted|git|local) ;;
    *)
      echo "Invalid dependency source '$1'; expected hosted, git, or local." >&2
      exit 2
      ;;
  esac
}

display_git_source() {
  local url="$rohd_git_url"

  case "$url" in
    https://github.com/*)
      url="${url#https://}"
      url="${url%.git}"
      ;;
  esac
  printf '%s:%s\n' "$url" "$rohd_git_ref"
}

display_local_path() {
  local path="$1"

  case "$path" in
    "$HOME") printf '~\n' ;;
    "$HOME"/*) printf '~/%s\n' "${path#"$HOME"/}" ;;
    *) printf '%s\n' "$path" ;;
  esac
}

configure_git_source() {
  local spec="$1"
  local url
  local ref

  if [[ "$spec" != *:* ]]; then
    echo "Git source '$spec' must use the format repository:ref." >&2
    exit 2
  fi

  url="${spec%:*}"
  ref="${spec##*:}"
  if [[ -z "$url" || -z "$ref" || "$ref" == //* ]]; then
    echo "Git source '$spec' must use the format repository:ref." >&2
    exit 2
  fi

  case "$url" in
    github.com/*) url="https://$url" ;;
  esac

  rohd_git_url="$url"
  rohd_git_ref="$ref"
}

prompt_source_value() {
  local source="$1"
  local default_value
  local prompt
  local value

  if [[ "${SCHEMATIC_PROMPT_SOURCE_VALUE:-0}" != 1 ||
    "$source" == "hosted" ]]; then
    return
  fi
  if [[ ! -t 0 ]]; then
    echo "Interactive source prompting requires a terminal." >&2
    exit 2
  fi

  case "$source" in
    git)
      default_value="$(display_git_source)"
      prompt="Shared ROHD Git repository:ref: "
      ;;
    local)
      default_value="$(display_local_path "$rohd_path")"
      prompt="Shared local ROHD checkout path: "
      ;;
  esac

  IFS= read -e -r -i "$default_value" -p "$prompt" value
  ROHD_SOURCE_VALUE="${value:-$default_value}"
}

append_git_dependency() {
  local output="$1"
  local package="$2"
  local path="${3:-}"
  cat >>"$output" <<YAML
  $package:
    git:
      url: $rohd_git_url
      ref: $rohd_git_ref
YAML
  if [[ -n "$path" ]]; then
    printf '      path: %s\n' "$path" >>"$output"
  fi
}

generate_configured_overrides() {
  local output="$1"
  shift
  local widgets_path
  local navigator_path
  local package
  local source
  local overridden=0

  if [[ "$#" -eq 0 || "$(( $# % 2 ))" -ne 0 ]]; then
    echo "Usage: $0 configure <package> <hosted|git|local> ..." >&2
    exit 2
  fi

  cat >"$output" <<YAML
$marker
# This file is intentionally ignored by git.
dependency_overrides:
YAML

  while [[ "$#" -gt 0 ]]; do
    package="$1"
    source="$2"
    shift 2
    validate_source "$source"
    case "$package" in
      rohd)
        case "$source" in
          hosted) ;;
          git) append_git_dependency "$output" rohd; overridden=1 ;;
          local)
            resolve_rohd_path
            printf '  rohd:\n    path: %s\n' "$rohd_path" >>"$output"
            overridden=1
            ;;
        esac
        ;;
      rohd_hierarchy)
        case "$source" in
          hosted) ;;
          git)
            append_git_dependency \
              "$output" rohd_hierarchy packages/rohd_hierarchy
            overridden=1
            ;;
          local)
            resolve_rohd_path
            printf '  rohd_hierarchy:\n    path: %s/packages/rohd_hierarchy\n' \
              "$rohd_path" >>"$output"
            overridden=1
            ;;
        esac
        ;;
      rohd_devtools_widgets)
        case "$source" in
          hosted) ;;
          git)
            append_git_dependency \
              "$output" rohd_devtools_widgets packages/rohd_devtools_widgets
            overridden=1
            ;;
          local)
            resolve_rohd_path
            widgets_path="$(resolve_widgets_path)"
            [[ -f "$widgets_path/pubspec.yaml" ]] ||
              { echo "Missing local package: $widgets_path" >&2; exit 1; }
            printf '  rohd_devtools_widgets:\n    path: %s\n' \
              "$widgets_path" >>"$output"
            overridden=1
            ;;
        esac
        ;;
      rohd_source_navigator)
        case "$source" in
          hosted) ;;
          git)
            append_git_dependency \
              "$output" rohd_source_navigator packages/rohd_source_navigator
            overridden=1
            ;;
          local)
            resolve_rohd_path
            navigator_path="$(resolve_navigator_path)"
            [[ -f "$navigator_path/pubspec.yaml" ]] ||
              { echo "Missing local package: $navigator_path" >&2; exit 1; }
            printf '  rohd_source_navigator:\n    path: %s\n' \
              "$navigator_path" >>"$output"
            overridden=1
            ;;
        esac
        ;;
      *)
        echo "Unsupported package '$package'." >&2
        echo "Supported packages: rohd, rohd_hierarchy, rohd_devtools_widgets, rohd_source_navigator." >&2
        exit 2
        ;;
    esac
  done

  configured_overrides_required="$overridden"
  chmod 0644 "$output"
}

install_configured_overrides() {
  local generated_overrides="$1"

  backup_overrides
  if [[ "$configured_overrides_required" == "0" ]]; then
    rm -f -- "$generated_overrides"
    echo "All configured dependencies use pubspec.yaml; no override file is needed."
  else
    mv -- "$generated_overrides" "$overrides"
    echo "Wrote $overrides with non-hosted package sources only."
  fi
}

write_configured_overrides() {
  local generated_overrides

  ensure_managed_or_absent
  create_temporary_file
  generated_overrides="$temporary_file"
  generate_configured_overrides "$generated_overrides" "$@"
  install_configured_overrides "$generated_overrides"
}

write_group_configuration() {
  local group="${1:-}"
  local source="${2:-}"
  local rohd_source="hosted"
  local hierarchy_source="hosted"
  local widgets_source="hosted"
  local navigator_source="hosted"
  local package
  local saved_source
  local generated_overrides
  local generated_state

  if [[ "$#" -ne 2 ]]; then
    echo "Usage: $0 configure-group <rohd|package|widget|all> <hosted|git|local>" >&2
    exit 2
  fi
  validate_source "$source"

  case "$source" in
    git)
      echo "Git repository/ref is shared by all Git-backed dependency groups."
      ;;
    local)
      echo "Local checkout path is shared by all Local-backed dependency groups."
      ;;
    hosted) ;;
  esac

  if [[ -f "$source_state" ]]; then
    while IFS='=' read -r package saved_source; do
      case "$package" in
        rohd) rohd_source="$saved_source" ;;
        rohd_hierarchy) hierarchy_source="$saved_source" ;;
        rohd_devtools_widgets) widgets_source="$saved_source" ;;
        rohd_source_navigator) navigator_source="$saved_source" ;;
        git_url)
          [[ -v ROHD_GIT_URL ]] || rohd_git_url="$saved_source"
          ;;
        git_ref)
          [[ -v ROHD_GIT_REF ]] || rohd_git_ref="$saved_source"
          ;;
        local_path)
          [[ -v ROHD_LOCAL_PATH ]] || rohd_path="$saved_source"
          ;;
      esac
    done <"$source_state"
  fi

  prompt_source_value "$source"

  case "$source" in
    git)
      if [[ -n "${ROHD_SOURCE_VALUE:-}" ]]; then
        configure_git_source "$ROHD_SOURCE_VALUE"
      fi
      ;;
    local)
      if [[ -n "${ROHD_SOURCE_VALUE:-}" ]]; then
        rohd_path="$ROHD_SOURCE_VALUE"
      fi
      ;;
    hosted) ;;
  esac

  case "$group" in
    rohd) rohd_source="$source" ;;
    package)
      hierarchy_source="$source"
      navigator_source="$source"
      ;;
    widget)
      hierarchy_source="$source"
      widgets_source="$source"
      navigator_source="$source"
      ;;
    all)
      rohd_source="$source"
      hierarchy_source="$source"
      widgets_source="$source"
      navigator_source="$source"
      ;;
    *)
      echo "Invalid dependency group '$group'; expected rohd, package, widget, or all." >&2
      exit 2
      ;;
  esac

  ensure_managed_or_absent
  create_temporary_file
  generated_state="$temporary_file"
  generate_source_state \
    "$generated_state" \
    "$rohd_source" \
    "$hierarchy_source" \
    "$widgets_source" \
    "$navigator_source"

  create_temporary_file
  generated_overrides="$temporary_file"
  generate_configured_overrides "$generated_overrides" \
    rohd "$rohd_source" \
    rohd_hierarchy "$hierarchy_source" \
    rohd_devtools_widgets "$widgets_source" \
    rohd_source_navigator "$navigator_source"
  install_configured_overrides "$generated_overrides"
  mv -- "$generated_state" "$source_state"
}

generate_source_state() {
  local output="$1"
  local rohd_source="$2"
  local hierarchy_source="$3"
  local widgets_source="$4"
  local navigator_source="$5"

  cat >"$output" <<STATE
rohd=$rohd_source
rohd_hierarchy=$hierarchy_source
rohd_devtools_widgets=$widgets_source
rohd_source_navigator=$navigator_source
git_url=$rohd_git_url
git_ref=$rohd_git_ref
local_path=$rohd_path
STATE
  chmod 0644 "$output"
}

persist_source_state() {
  local generated_state
  create_temporary_file
  generated_state="$temporary_file"
  generate_source_state "$generated_state" "$@"
  mv -- "$generated_state" "$source_state"
}

write_overrides() {
  local local_rohd="$1"
  local local_extension="$2"

  ensure_managed_or_absent

  if [[ "$local_rohd" == "no" && "$local_extension" == "no" ]]; then
    if [[ -f "$overrides" ]]; then
      backup_overrides
    else
      echo "No $overrides present; using hosted dependencies from pubspec.yaml."
    fi
    return
  fi

  resolve_rohd_path
  ensure_local_rohd_packages "$local_extension"

  cat > "$overrides" <<YAML
$marker
# This file is intentionally ignored by git.
dependency_overrides:
YAML

  if [[ "$local_rohd" == "yes" ]]; then
    cat >> "$overrides" <<YAML
  rohd:
    path: $rohd_path
YAML
  fi

  if [[ "$local_rohd" == "yes" || "$local_extension" == "yes" ]]; then
    cat >> "$overrides" <<YAML
  rohd_hierarchy:
    path: $rohd_path/packages/rohd_hierarchy
YAML
  fi

  if [[ "$local_extension" == "yes" ]]; then
    local widgets_path
    local navigator_path
    widgets_path="$(resolve_widgets_path)"
    navigator_path="$(resolve_navigator_path)"
    cat >> "$overrides" <<YAML
  rohd_devtools_widgets:
    path: $widgets_path
  rohd_source_navigator:
    path: $navigator_path
YAML
  fi

  echo "Wrote $overrides for $mode mode."
}

case "$mode" in
  configure)
    shift
    write_configured_overrides "$@"
    ;;
  configure-group) write_group_configuration "${2:-}" "${3:-}" ;;
  manifest|hr-he)
    write_overrides no no
    rm -f -- "$source_state"
    ;;
  local-rohd|lr-he)
    write_overrides yes no
    persist_source_state local local hosted hosted
    ;;
  local-extension|hr-le)
    write_overrides no yes
    persist_source_state hosted local local local
    ;;
  local-all|lr-le)
    write_overrides yes yes
    persist_source_state local local local local
    ;;
  show)
    if [[ -f "$overrides" ]]; then
      cat "$overrides"
    else
      echo "No $overrides present; using hosted dependencies from pubspec.yaml."
    fi
    ;;
  -h|--help|help|"") usage ;;
  *) usage >&2; exit 2 ;;
esac
