#!/usr/bin/env bash

# Copyright (C) 2026 Intel Corporation
# SPDX-License-Identifier: BSD-3-Clause
#
# schematic_dev_mode.sh
# Configures Schematic Viewer development dependency overrides.
#
# 2026 August
# Author: Desmond Kirkpatrick <desmond.a.kirkpatrick@intel.com>

set -euo pipefail

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
viewer_dir="$(cd -- "$script_dir/.." && pwd)"
cd "$viewer_dir"

mode="${1:-}"
overrides="pubspec_overrides.yaml"
source_state=".schematic_dependency_sources"
marker="# Generated by scripts/schematic_dev_mode.sh. Do not edit by hand."
default_rohd_path="$HOME/release/rohd"
rohd_git_url="${ROHD_GIT_URL:-https://github.com/intel/rohd.git}"
rohd_git_ref="${ROHD_GIT_REF:-main}"

dependency_constraint() {
  local package="$1"
  awk -v package="$package" '
    $1 == package ":" { print $2; exit }
  ' pubspec.yaml
}

rohd_hosted_constraint="${ROHD_HOSTED_CONSTRAINT:-$(dependency_constraint rohd)}"
hierarchy_hosted_constraint="${ROHD_HIERARCHY_HOSTED_CONSTRAINT:-$(dependency_constraint rohd_hierarchy)}"
widgets_hosted_constraint="${ROHD_WIDGETS_HOSTED_CONSTRAINT:-$(dependency_constraint rohd_devtools_widgets)}"
navigator_hosted_constraint="${ROHD_NAVIGATOR_HOSTED_CONSTRAINT:-$(dependency_constraint rohd_source_navigator)}"

for dependency in rohd rohd_hierarchy rohd_devtools_widgets rohd_source_navigator; do
  if [[ -z "$(dependency_constraint "$dependency")" ]]; then
    echo "Could not find $dependency in pubspec.yaml." >&2
    exit 1
  fi
done

rohd_path="${ROHD_LOCAL_PATH:-$default_rohd_path}"

usage() {
  cat <<'USAGE'
Usage: scripts/schematic_dev_mode.sh <mode>

Configure individual package sources:
  scripts/schematic_dev_mode.sh configure <package> <source> ...
  where each source is hosted, git, or local.

For example:
  scripts/schematic_dev_mode.sh configure rohd git rohd_hierarchy local

Modes:
  manifest         Disable overrides and use pubspec.yaml sources.
  configure-group  Configure one dependency group or all dependencies.
  local-rohd       Local ROHD + hierarchy; Git DevTools-extension packages.
  local-extension  Pub.dev ROHD; local hierarchy + DevTools-extension packages.
  local-all        Local ROHD, hierarchy, and DevTools-extension packages.
  show             Print the current generated override file, if present.

The default local ROHD checkout is ~/release/rohd.
Set ROHD_LOCAL_PATH to use a different checkout.

Git sources use ROHD_GIT_URL and default to the main branch. Set ROHD_GIT_REF
to use another branch or tag. Hosted constraints are read from pubspec.yaml
and can be overridden with the package-specific ROHD_*_HOSTED_CONSTRAINT
variables.

With no overrides, the hosted dependencies in pubspec.yaml are used.

Legacy aliases hr-he, lr-he, hr-le, and lr-le remain supported.
USAGE
}

ensure_managed_or_absent() {
  if [[ -f "$overrides" ]] && ! grep -qxF "$marker" "$overrides"; then
    echo "$overrides exists and was not generated by scripts/schematic_dev_mode.sh." >&2
    echo "Move or remove it before switching development modes." >&2
    exit 1
  fi
}

backup_overrides() {
  local backup="$overrides.disabled"
  local suffix=1

  if [[ ! -f "$overrides" ]]; then
    return
  fi

  while [[ -e "$backup" ]]; do
    backup="$overrides.disabled.$suffix"
    suffix=$((suffix + 1))
  done
  mv -- "$overrides" "$backup"
  echo "Saved the previous $overrides as $backup."
}

resolve_rohd_path() {
  case "$rohd_path" in
    '~') rohd_path="$HOME" ;;
    \~/*) rohd_path="$HOME/${rohd_path:2}" ;;
  esac
  if [[ ! -f "$rohd_path/pubspec.yaml" ]] || ! grep -qx 'name: rohd' "$rohd_path/pubspec.yaml"; then
    echo "Could not find a ROHD checkout at $rohd_path." >&2
    echo "Set ROHD_LOCAL_PATH to a checkout rooted at the rohd package." >&2
    exit 1
  fi
  rohd_path="$(cd -- "$rohd_path" && pwd)"
}

ensure_local_rohd_packages() {
  local require_extension="$1"
  local missing=0

  if [[ ! -f "$rohd_path/packages/rohd_hierarchy/pubspec.yaml" ]]; then
    echo "Missing local ROHD package: $rohd_path/packages/rohd_hierarchy/pubspec.yaml" >&2
    missing=1
  fi

  if [[ "$require_extension" == "yes" ]]; then
    local widgets_path="$rohd_path/packages/rohd_devtools_widgets"
    if [[ ! -f "$widgets_path/pubspec.yaml" ]]; then
      widgets_path="$rohd_path/rohd_devtools_extension/packages/rohd_devtools_widgets"
    fi
    local navigator_path="$rohd_path/packages/rohd_source_navigator"
    if [[ ! -f "$navigator_path/pubspec.yaml" ]]; then
      navigator_path="$rohd_path/rohd_extension/dart"
    fi
    for package_path in "$widgets_path/pubspec.yaml" \
      "$navigator_path/pubspec.yaml"; do
      if [[ ! -f "$package_path" ]]; then
        echo "Missing local ROHD package: $package_path" >&2
        missing=1
      fi
    done
  fi

  if [[ "$missing" != "0" ]]; then
    echo "Use a ROHD checkout with the split-package layout, or choose the manifest mode." >&2
    exit 1
  fi
}

validate_source() {
  case "$1" in
    hosted|git|local) ;;
    *)
      echo "Invalid dependency source '$1'; expected hosted, git, or local." >&2
      exit 2
      ;;
  esac
}

append_git_dependency() {
  local package="$1"
  local path="${2:-}"
  cat >>"$overrides" <<YAML
  $package:
    git:
      url: $rohd_git_url
      ref: $rohd_git_ref
YAML
  if [[ -n "$path" ]]; then
    printf '      path: %s\n' "$path" >>"$overrides"
  fi
}

write_configured_overrides() {
  local widgets_path
  local package
  local source
  local overridden=0

  if [[ "$#" -eq 0 || "$(( $# % 2 ))" -ne 0 ]]; then
    echo "Usage: $0 configure <package> <hosted|git|local> ..." >&2
    exit 2
  fi
  ensure_managed_or_absent
  backup_overrides

  cat >"$overrides" <<YAML
$marker
# This file is intentionally ignored by git.
dependency_overrides:
YAML

  while [[ "$#" -gt 0 ]]; do
    package="$1"
    source="$2"
    shift 2
    validate_source "$source"
    case "$package" in
      rohd)
        case "$source" in
          hosted) ;;
          git) append_git_dependency rohd; overridden=1 ;;
          local)
            resolve_rohd_path
            printf '  rohd:\n    path: %s\n' "$rohd_path" >>"$overrides"
            overridden=1
            ;;
        esac
        ;;
      rohd_hierarchy)
        case "$source" in
          hosted) ;;
          git) append_git_dependency rohd_hierarchy packages/rohd_hierarchy; overridden=1 ;;
          local)
            resolve_rohd_path
            printf '  rohd_hierarchy:\n    path: %s/packages/rohd_hierarchy\n' "$rohd_path" >>"$overrides"
            overridden=1
            ;;
        esac
        ;;
      rohd_devtools_widgets)
        case "$source" in
          hosted) ;;
          git) append_git_dependency rohd_devtools_widgets packages/rohd_devtools_widgets; overridden=1 ;;
          local)
            resolve_rohd_path
            widgets_path="$rohd_path/packages/rohd_devtools_widgets"
            if [[ ! -f "$widgets_path/pubspec.yaml" ]]; then
              widgets_path="$rohd_path/rohd_devtools_extension/packages/rohd_devtools_widgets"
            fi
            [[ -f "$widgets_path/pubspec.yaml" ]] ||
              { echo "Missing local package: $widgets_path" >&2; exit 1; }
            printf '  rohd_devtools_widgets:\n    path: %s\n' "$widgets_path" >>"$overrides"
            overridden=1
            ;;
        esac
        ;;
      rohd_source_navigator)
        case "$source" in
          hosted) ;;
          git) append_git_dependency rohd_source_navigator packages/rohd_source_navigator; overridden=1 ;;
          local)
            resolve_rohd_path
            navigator_path="$rohd_path/packages/rohd_source_navigator"
            if [[ ! -f "$navigator_path/pubspec.yaml" ]]; then
              navigator_path="$rohd_path/rohd_extension/dart"
            fi
            [[ -f "$navigator_path/pubspec.yaml" ]] ||
              { echo "Missing local package: $navigator_path" >&2; exit 1; }
            printf '  rohd_source_navigator:\n    path: %s\n' "$navigator_path" >>"$overrides"
            overridden=1
            ;;
        esac
        ;;
      *)
        echo "Unsupported package '$package'." >&2
        echo "Supported packages: rohd, rohd_hierarchy, rohd_devtools_widgets, rohd_source_navigator." >&2
        exit 2
        ;;
    esac
  done

  if [[ "$overridden" == "0" ]]; then
    rm -f -- "$overrides"
    echo "All configured dependencies use pubspec.yaml; no override file is needed."
  else
    echo "Wrote $overrides with non-hosted package sources only."
  fi
}

write_group_configuration() {
  local group="${1:-}"
  local source="${2:-}"
  local rohd_source="hosted"
  local hierarchy_source="hosted"
  local widgets_source="hosted"
  local navigator_source="hosted"
  local saved_git_ref=""
  local saved_local_path=""
  local package
  local saved_source

  if [[ "$#" -ne 2 ]]; then
    echo "Usage: $0 configure-group <rohd|package|widget|all> <hosted|git|local>" >&2
    exit 2
  fi
  validate_source "$source"

  if [[ -f "$source_state" ]]; then
    while IFS='=' read -r package saved_source; do
      case "$package" in
        rohd) rohd_source="$saved_source" ;;
        rohd_hierarchy) hierarchy_source="$saved_source" ;;
        rohd_devtools_widgets) widgets_source="$saved_source" ;;
        rohd_source_navigator) navigator_source="$saved_source" ;;
        git_ref) saved_git_ref="$saved_source" ;;
        local_path) saved_local_path="$saved_source" ;;
      esac
    done <"$source_state"
  fi

  case "$source" in
    git)
      rohd_git_ref="${ROHD_GIT_REF:-main}"
      rohd_path="${saved_local_path:-$default_rohd_path}"
      ;;
    local)
      rohd_git_ref="${saved_git_ref:-main}"
      rohd_path="${ROHD_LOCAL_PATH:-$default_rohd_path}"
      ;;
    hosted)
      rohd_git_ref="${saved_git_ref:-main}"
      rohd_path="${saved_local_path:-$default_rohd_path}"
      ;;
  esac

  case "$group" in
    rohd) rohd_source="$source" ;;
    package)
      hierarchy_source="$source"
      navigator_source="$source"
      ;;
    widget)
      hierarchy_source="$source"
      widgets_source="$source"
      navigator_source="$source"
      ;;
    all)
      rohd_source="$source"
      hierarchy_source="$source"
      widgets_source="$source"
      navigator_source="$source"
      ;;
    *)
      echo "Invalid dependency group '$group'; expected rohd, package, widget, or all." >&2
      exit 2
      ;;
  esac

  cat >"$source_state" <<STATE
rohd=$rohd_source
rohd_hierarchy=$hierarchy_source
rohd_devtools_widgets=$widgets_source
rohd_source_navigator=$navigator_source
git_ref=$rohd_git_ref
local_path=$rohd_path
STATE

  write_configured_overrides \
    rohd "$rohd_source" \
    rohd_hierarchy "$hierarchy_source" \
    rohd_devtools_widgets "$widgets_source" \
    rohd_source_navigator "$navigator_source"
}

write_overrides() {
  local local_rohd="$1"
  local local_extension="$2"

  ensure_managed_or_absent

  if [[ "$local_rohd" == "no" && "$local_extension" == "no" ]]; then
    if [[ -f "$overrides" ]]; then
      backup_overrides
    else
      echo "No $overrides present; using hosted dependencies from pubspec.yaml."
    fi
    return
  fi

  resolve_rohd_path
  ensure_local_rohd_packages "$local_extension"

  cat > "$overrides" <<YAML
$marker
# This file is intentionally ignored by git.
dependency_overrides:
YAML

  if [[ "$local_rohd" == "yes" ]]; then
    cat >> "$overrides" <<YAML
  rohd:
    path: $rohd_path
YAML
  fi

  if [[ "$local_rohd" == "yes" || "$local_extension" == "yes" ]]; then
    cat >> "$overrides" <<YAML
  rohd_hierarchy:
    path: $rohd_path/packages/rohd_hierarchy
YAML
  fi

  if [[ "$local_extension" == "yes" ]]; then
    local navigator_path="$rohd_path/packages/rohd_source_navigator"
    if [[ ! -f "$navigator_path/pubspec.yaml" ]]; then
      navigator_path="$rohd_path/rohd_extension/dart"
    fi
    cat >> "$overrides" <<YAML
  rohd_devtools_widgets:
    path: $rohd_path/rohd_devtools_extension/packages/rohd_devtools_widgets
  rohd_source_navigator:
    path: $navigator_path
YAML
  fi

  echo "Wrote $overrides for $mode mode."
}

case "$mode" in
  configure)
    shift
    write_configured_overrides "$@"
    ;;
  configure-group) write_group_configuration "${2:-}" "${3:-}" ;;
  manifest|hr-he)
    write_overrides no no
    rm -f -- "$source_state"
    ;;
  local-rohd|lr-he) write_overrides yes no ;;
  local-extension|hr-le) write_overrides no yes ;;
  local-all|lr-le) write_overrides yes yes ;;
  show)
    if [[ -f "$overrides" ]]; then
      cat "$overrides"
    else
      echo "No $overrides present; using hosted dependencies from pubspec.yaml."
    fi
    ;;
  -h|--help|help|"") usage ;;
  *) usage >&2; exit 2 ;;
esac
