#!/usr/bin/env bash

# Copyright (C) 2026 Intel Corporation
# SPDX-License-Identifier: BSD-3-Clause
#
# schematic_dev_mode.sh
# Configures Schematic Viewer development dependency overrides.
#
# 2026 August
# Author: Desmond Kirkpatrick <desmond.a.kirkpatrick@intel.com>

set -euo pipefail

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
viewer_dir="$(cd -- "$script_dir/.." && pwd)"
cd "$viewer_dir"

mode="${1:-}"
overrides="pubspec_overrides.yaml"
marker="# Generated by scripts/schematic_dev_mode.sh. Do not edit by hand."
default_rohd_path="$HOME/release/rohd"

if [[ -n "${ROHD_LOCAL_PATH:-}" ]]; then
  rohd_path="$ROHD_LOCAL_PATH"
else
  rohd_path="$default_rohd_path"
fi

usage() {
  cat <<'USAGE'
Usage: scripts/schematic_dev_mode.sh <mode>

Modes:
  manifest         Use pubspec.yaml sources: pub.dev ROHD + Git ROHD packages.
  local-rohd       Local ROHD + hierarchy; Git DevTools-extension packages.
  local-extension  Pub.dev ROHD; local hierarchy + DevTools-extension packages.
  local-all        Local ROHD, hierarchy, and DevTools-extension packages.
  show             Print the current generated override file, if present.

The default local ROHD checkout is ~/release/rohd.
Set ROHD_LOCAL_PATH to use a different checkout.

Legacy aliases hr-he, lr-he, hr-le, and lr-le remain supported.
USAGE
}

ensure_managed_or_absent() {
  if [[ -f "$overrides" ]] && ! grep -qxF "$marker" "$overrides"; then
    echo "$overrides exists and was not generated by scripts/schematic_dev_mode.sh." >&2
    echo "Move or remove it before switching development modes." >&2
    exit 1
  fi
}

resolve_rohd_path() {
  if [[ ! -f "$rohd_path/pubspec.yaml" ]] || ! grep -qx 'name: rohd' "$rohd_path/pubspec.yaml"; then
    echo "Could not find a ROHD checkout at $rohd_path." >&2
    echo "Set ROHD_LOCAL_PATH to a checkout rooted at the rohd package." >&2
    exit 1
  fi
  rohd_path="$(cd -- "$rohd_path" && pwd)"
}

ensure_local_rohd_packages() {
  local require_extension="$1"
  local missing=0

  if [[ ! -f "$rohd_path/packages/rohd_hierarchy/pubspec.yaml" ]]; then
    echo "Missing local ROHD package: $rohd_path/packages/rohd_hierarchy/pubspec.yaml" >&2
    missing=1
  fi

  if [[ "$require_extension" == "yes" ]]; then
    for package_path in \
      "$rohd_path/rohd_devtools_extension/packages/rohd_devtools_widgets/pubspec.yaml" \
      "$rohd_path/rohd_extension/dart/pubspec.yaml"; do
      if [[ ! -f "$package_path" ]]; then
        echo "Missing local ROHD package: $package_path" >&2
        missing=1
      fi
    done
  fi

  if [[ "$missing" != "0" ]]; then
    echo "Use a ROHD checkout with the split-package layout, or choose the manifest mode." >&2
    exit 1
  fi
}

write_overrides() {
  local local_rohd="$1"
  local local_extension="$2"

  ensure_managed_or_absent

  if [[ "$local_rohd" == "no" && "$local_extension" == "no" ]]; then
    rm -f "$overrides"
    echo "Removed $overrides; using hosted dependencies from pubspec.yaml."
    return
  fi

  resolve_rohd_path
  ensure_local_rohd_packages "$local_extension"

  cat > "$overrides" <<YAML
$marker
# This file is intentionally ignored by git.
dependency_overrides:
YAML

  if [[ "$local_rohd" == "yes" ]]; then
    cat >> "$overrides" <<YAML
  rohd:
    path: $rohd_path
YAML
  fi

  if [[ "$local_rohd" == "yes" || "$local_extension" == "yes" ]]; then
    cat >> "$overrides" <<YAML
  rohd_hierarchy:
    path: $rohd_path/packages/rohd_hierarchy
YAML
  fi

  if [[ "$local_extension" == "yes" ]]; then
    cat >> "$overrides" <<YAML
  rohd_devtools_widgets:
    path: $rohd_path/rohd_devtools_extension/packages/rohd_devtools_widgets
  rohd_source_navigator:
    path: $rohd_path/rohd_extension/dart
YAML
  fi

  echo "Wrote $overrides for $mode mode."
}

case "$mode" in
  manifest|hr-he) write_overrides no no ;;
  local-rohd|lr-he) write_overrides yes no ;;
  local-extension|hr-le) write_overrides no yes ;;
  local-all|lr-le) write_overrides yes yes ;;
  show)
    if [[ -f "$overrides" ]]; then
      cat "$overrides"
    else
      echo "No $overrides present; using hosted dependencies from pubspec.yaml."
    fi
    ;;
  -h|--help|help|"") usage ;;
  *) usage >&2; exit 2 ;;
esac
